name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 16
      
      - name: Install dependencies
        run: |
          npm ci
          cd functions && npm ci
      
      - run: npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Update Firestore database with train data
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://us-central1-irishrailtracker.cloudfunctions.net/postLiveTrainData'
          method: 'GET'
      
      - name: Update Firestore database with station data
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://us-central1-irishrailtracker.cloudfunctions.net/postStationData'
          method: 'GET'