name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 16
      
      - name: Install dependencies
        run: |
          npm ci
          cd functions && npm ci
      
      - name: Firebase deploy
        run: npm run build && firebase deploy